title: motor-robot-buggy-scratch
hero_image: images/banner.png
description: motor-robot-buggy-scratch description
version: 5
listed: false
copyedit: false
last_tested: "2019-11-05"
steps:
  - title: Introduction
  - title: Set up your motors
  - title: Test the motors with Scratch
  - title: What are motors for?
  - title: "Challenge: Adapt your motor project"
    challenge: true
  - title: Reaction game
  - title: How to make a robot buggy
  - title: Remote Scratch using Real VNC
  - title: Scratch visual remote
  - title: Alternative visual remote
  - title: Scratch keyboard remote
  - title: Programmed maze journeys
  - title: What next?
