title: motor-robot-buggy-scratch
hero_image: images/banner.png
description: motor-robot-buggy-scratch description
version: 4
listed: false
copyedit: false
last_tested: "2019-11-05"
steps:
  - title: Introduction
  - title: Setting up your motors
  - title: Testing the motors with Scratch
  - title: What are motors for?
  - title: "Challenge: Adapting your motor project"
    challenge: true
  - title: Reaction game
  - title: Making a robot buggy
  - title: Remote Scratch using Real VNC
  - title: Visual Scratch remote
  - title: 
